//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO5027
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image_Tbl
    {
        public int Image_ID { get; set; }
        public string Image_Name { get; set; }
        public Nullable<int> Image_Width { get; set; }
        public Nullable<int> Image_Height { get; set; }
        public string Image_Extension { get; set; }
        public string Image_Alternate { get; set; }
    }
}
